# Generated by Django 3.0.6 on 2020-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='steamid',
            field=models.CharField(max_length=17),
        ),
    ]
