# Generated by Django 3.0.6 on 2020-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200526_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.SlugField(max_length=255),
        ),
    ]
