# Generated by Django 3.0.6 on 2020-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200530_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weapon_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
