# Generated by Django 3.0.6 on 2020-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_item_weapon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_url',
            field=models.SlugField(max_length=255),
        ),
    ]
