# Generated by Django 3.0.6 on 2020-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200604_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wear', models.CharField(max_length=255)),
                ('weapon_name', models.CharField(max_length=255)),
                ('icon_url', models.SlugField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='market_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weapon_name',
        ),
        migrations.AddField(
            model_name='item',
            name='avatar',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
