# Generated by Django 3.0.6 on 2020-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200604_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avatar',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
