# Generated by Django 3.0.6 on 2020-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_item_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
