# Generated by Django 3.0.6 on 2020-06-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='current_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
