# Generated by Django 3.0.6 on 2020-06-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='authkey',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='avatarfull',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='avatarmedium',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='profileurl',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='tradeurl',
        ),
    ]
